scalar DateTime

type Time {
  _id: ID!
  last: DateTime!
  user: User!
}

input TimeInput {
  last: DateTime!
  user: ID!
}

type Query {
  getTimes: [Time!]!
  getTime(id: ID!): Time!
}

type Mutation {
  createTime(data: TimeInput!): Time!
  updateTime(id: ID!, data: TimeInput!): Time!
  deleteTime(id: ID!): Boolean
}
