scalar DateTime

type Time {
  _id: ID!
  description: String!
  created: DateTime!
  user: User!
}

input TimeInput {
  description: String!
  user: ID!
}

type Query {
  getTimes: [Time!]!
  getTime(id: ID!): Time!
}

type Mutation {
  createTime(data: TimeInput!): Time!
  updateTime(id: ID!, data: TimeInput!): Time!
  deleteTime(id: ID!): Boolean
}
